### ISSUE TITLE
Need .NET sample code for JWT authentication, similar to https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/JWT/samples/samples.md.

### ISSUE THREAD

**Issue by nids** [AdobeDocs/adobeio-auth#25]

**Comment by hirenoble** [comment]
Hi @nids,

Thank you for request. I would be happy to add .NET sample for JWT authentication. I'll notify you once it is added.

Thanks,
Hiren

**Comment by hirenoble** [comment]
@nids Please find the sample code here: https://github.com/AdobeDocs/adobeio-auth/tree/master/JWT/samples/adobe-jwt-dotnet

Let me know if you see any issues.

Thanks,
Hiren

**Comment by vm57us** [comment]
The problem with this code is that it's using third party DLLs and not native ones. These libraries don't have strong names so is not possible to add them into the assemblies to use in Script Tasks in SSIS.
Does anyone has any code that works with native .net libraries?
