### ISSUE TITLE
Certificate issue in Adobe I/O Console

### ISSUE THREAD

**Issue by AliiBenYedder** [AdobeDocs/adobeio-auth#27]
Hello,

I was trying to create an integration to Access the User Management API! I followed the [documentation](https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/AuthenticationOverview/ServiceAccountIntegration.md) of how to generate a certificate!! But when I try to upload the Certificate I get "Argh, your certificate is not valid! Check this url for a tutorial on how to generate a valid certificate. ( request debug id: 49ede89d-6221-4a9f-bd9f-d3003a4ad30e )".
So I've tried to generate a certificate using an online generator and didn't work neither!

**Comment by macdonst** [comment]
@AliiBenYedder are you on a PC, Mac or Linux? 

Another common mistake is folks will upload the private key instead of the public key.

**Comment by AliiBenYedder** [comment]
Hey @macdonst !! 
I'm on PC and I'm not uploading the Private key.

**Comment by hirenoble** [comment]
Hi @AliiBenYedder,

I saved the certificate as certificate.crt file and tried to upload in an integration. It worked fine for me.
![image](https://user-images.githubusercontent.com/3747836/56223891-dbdc0300-602b-11e9-9817-d6dd06ad2ae1.png)

Please ensure you copy the entire content including `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`

**Comment by AliiBenYedder** [comment]
Hi,
Thanks for the reply !! I don't know why it didn't work with me!! Maybe because of the file's name!! I will try it and keep you in touch.

**Comment by AliiBenYedder** [comment]
So I've tried it out!! it didn't work! I've tried to rename the file to certificate.crt and uploading it but I still getting the same error.
For more information: 
![error](https://user-images.githubusercontent.com/49684725/56239374-14fa8e80-6091-11e9-892b-f08f833c0728.png)

**Comment by hirenoble** [comment]
@AliiBenYedder if you have some time now let's have a quick call: https://bluejeans.com/3853452738

**Comment by AliiBenYedder** [comment]
@hirenoble That would be great!! You can comment the link here when you have the time.

**Comment by AliiBenYedder** [comment]
We've tried serveral additional things now including different networks like via mobile phone or our home networks to make sure, the problem doesn't lie within our company network. Furhtermore we tired creating new certificates, excluding special characters etc, also tried renaming the file in serveral ways, but all to no avail.

In a former replay, you used the provided certificate succesfully, but what i'd like to know is, which service you chose to integrate with for your test, as it is crucial for us, to integrate with the Adobe User Management API.

Thanks in advance

**Comment by macdonst** [comment]
@AliiBenYedder there is a bug here for sure. I've run into another user with exactly the same scenario. We've escalated the issue up the chain as we are not sure if the issue is with the console or user management api. We'll get back to you soon.

**Comment by AliiBenYedder** [comment]
@macdonst Thanks! Could you please let us know once you get some additional infos!!
Thanks

**Comment by macdonst** [comment]
@AliiBenYedder will do, I'm just waiting for the west coast of the USA to wake up so I can pounce on them.

**Comment by hirenoble** [comment]
@AliiBenYedder Are you available for a call now? It will help us in identifying the root cause.
https://bluejeans.com/3853452738

**Comment by macdonst** [comment]
@AliiBenYedder Quick follow up question, are you a system administrator for the org or are you using the new developer role feature?

**Comment by AliiBenYedder** [comment]
I'm not a system administrator!! I'm trying to develop an application that consumes the service through its API!! Sorry for the late answer!

**Comment by AliiBenYedder** [comment]
@hirenoble we can do a quick call if you're available

**Comment by hirenoble** [comment]
Joining https://bluejeans.com/3853452738

**Comment by AliiBenYedder** [comment]
Joining in 5 minutes

**Comment by macdonst** [comment]
@AliiBenYedder we've found this to be a bug in the Adobe I/O Console.

cc: @wildabeast

**Comment by wildabeast** [comment]
After some investigation, it appears that UMAPI should be disabled for you as it is not available for non-enterprise organizations.

**Comment by AliiBenYedder** [comment]
@macdonst @wildabeast Thanks for your support!
I guess I need to find another solution. Is there any other API to use to get the users and the subscriptions in my account?

**Comment by slapdashengineering** [comment]
I'm seeing this issue as well, and it's extra-special weird because we have two linked accounts and it works fine in one but not the other.       I have system admin rights, and in fact have tried a second account just in case mine was bugged, but no joy.

**Comment by slapdashengineering** [comment]
@hirenoble @wildabeast is there any timeline on a resolution for this?

**Comment by wildabeast** [comment]
@slapdashengineering the intent of the UM API is to manage users in an Enterprise Org, so as I see it, a User Management API doesn't really have a context outside of an Enterprise Org . so I can't help but wonder what your use case is?

**Comment by wildabeast** [comment]
hrm on second thought I guess you could be attempting to manage users in non-Enterprise org (I forgot that was a thing). unfortunately I think the UMAPI service is only provided as a service to Enterprise-level subscriptions, and so I'm afraid I just don't really have a solution for you as a non-Enterprise user

**Comment by slapdashengineering** [comment]
@wildabeast I may have had a failure in github etiquette for jumping into someone else's thread, so if I should make a new issue let me know; I'm actually part of an enterprise account looking to streamline our user management.  We have two "organizations" in the admin portal, and I can make an integration in one of them (with no users or licenses), but I can't make an integration in our "organization" that has all the licenses attached to it.

**Comment by k16admin** [comment]
I'm sorry...same issu here. I'm using the admin account from creative cloud for teams. Certificate not valid :(

Here's the request debug id: 53549769-7397-4d3e-8a51-b4e47e862a1e
