### ISSUE TITLE
Make JWT recommendation more prominent

### ISSUE THREAD

**Issue by macdonst** [AdobeDocs/adobeio-auth#40]
Could the statements starting with Recommendation be starting on a separate line within this table cell ?

**Comment by fmeschbe** [comment]
Thanks @macdonst. How about adding a `<br/>`  (which is what I typically do in these situations, albeit in plain GitHub pages markdown. Don't know about the technology used here).

**Comment by macdonst** [comment]
@fmeschbe I think we will need to convert the table from markdown to a HTML table. I believe that Kirby can handle that and it will allow us to use a `<br/>`. Putting out some other 🔥 first.
