### ISSUE TITLE
JWT Exchange via Python not working

### ISSUE THREAD

**Issue by rola-23** [AdobeDocs/adobeio-auth#41]
Hi,

When executing the Python script for the JWT Exchange, an encoding error is coming :  **jwttoken = jwt.encode(jwtPayloadJson, private_key, algorithm='RS256').**

This is replicable for multiple Integrations across multiple Orgs.

**Comment by hirenoble** [comment]
Hi @rola-23,

Apologies for the delayed response, I have validated the python code sample and able to generate the access token. Make sure you are following the instructions correctly. Let me know if you are still facing the issue.

![image](https://user-images.githubusercontent.com/3747836/71042771-e7ffef00-20e9-11ea-8c74-73eeb721e499.png)

**Comment by davedavis** [comment]
@hirenoble 
I have a fix for this. Can I submit a PR? If so, which branch should I submit it to?

**Comment by macdonst** [comment]
@davedavis to stage please

**Comment by davedavis** [comment]
Thanks @macdonst 
I submitted it here: https://github.com/AdobeDocs/adobeio-auth/pull/53

It's my first real PR so please excuse any major issues. Very much open to any feedback you have and happy to correct, reformat or improve in any way you advise.
