### ISSUE TITLE
System.Security.Cryptography.CryptographicException: Invalid provider type specified.

### ISSUE THREAD

**Issue by devinnov** [AdobeDocs/adobeio-auth#42]
Just tried to deploy to azure and i had many issues like:
System.Security.Cryptography.CryptographicException: Invalid provider type specified.

The solution was adding:
var cert = new X509Certificate2("xxxx.pfx", "xxxx", **X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable)**;

**Comment by hirenoble** [comment]
@devinnov Thanks! We will test it out and update the solution.
