### ISSUE TITLE
Api Key is invalid

### ISSUE THREAD

**Issue by Lolita1001** [AdobeDocs/adobeio-auth#54]
Hey,

I'm trying to use the Adobe Lightroom API,  but I'm getting a response to a [POST request](https://adobedocs.github.io/lightroom-api-docs/#api-presets-presets_post). 
> {
>  "error_code": "403003",
>  "message": "Api Key is invalid"
> } '

Token generated from client_id and secret_key, but in "Scopes" field "openid" by default, any other value leads to Authorization error

In a POST request, I use Access Token and Client Id

Where am I wrong?

**Comment by jdegardeyn** [comment]
Hey did you ever solve this?  I have the same issue

**Comment by jessiahr** [comment]
As do I, It seems like these APIs may be abandoned

**Comment by jessiahr** [comment]
@hirenoble Is this API still supported?
