### ISSUE TITLE
Generate permanent access token

### ISSUE THREAD

**Issue by marvic2409** [AdobeDocs/adobeio-auth#64]
I read through the docs and it seems that all tokens that are generated will either expire after 24 hours or if they are a refresh token, 2 weeks. I need a token to access my adobe stock licensing and I need it to be permanent so I can run it headless on a server. Is that possible to do?

**Comment by macdonst** [comment]
@marvic2409 the short answer is no. The longer answer is it depends if you are using OAuth or Service integration. Since you are doing headless I suspect you are doing a service integration. In this case you would generate a new JWT and exchange it for a bearer token once a day.
